name: Component-Test Action Responder

on: [repository_dispatch]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        if: github.event.action == 'do-component-test'
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
          echo "Event Type '${{ github.event.event_type }}'"
#      - name: Do Tests
#        if: github.event.action == 'do-component-test'
#        run: |
#          echo "Event Do my very difficult test"
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=false verify

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: false
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
###
      - name: Send Result Back
        if: always() && github.event.action == 'do-component-test'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TRIGGER_TEST1 }}
          repository: ${{ github.event.client_payload.repository }}
          event-type: my-result
          client-payload: '{"repository": "${{github.repository}}", "result": "true", "run-id": "${{github.run_id}}", "resultUrl": "https://github.com/${{github.repository}}/runs/${{github.run_id}}" }'