name: Component-Test Responder

on:
  repository_dispatch:
    types: [do-component-test]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
          echo "Event Type '${{ github.event.event_type }}'"

      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --no-transfer-progress -Dmaven.test.failure.ignore=false verify -P ${{ github.event.client_payload.type-test }}

      - name: ReportSurefire
        if: github.event.client_payload.type-test == 'all'
        uses: dorny/test-reporter@v1
        with:
          name: Maven Junit Tests
          path: target/surefire-reports/*Test.xml
          reporter: java-junit
          fail-on-error: false

      - name: ReportFailsafe
        uses: dorny/test-reporter@v1
        with:
          name: Maven Component/Integration Tests
          path: target/failsafe-reports/*Test.xml
          reporter: java-junit
          fail-on-error: false

      - name: Send Result Back
        if: always()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TRIGGER_TEST1 }}
          repository: ${{ github.event.client_payload.repository }}
          event-type: my-result
          client-payload: '{"repository": "${{github.repository}}", "result": "${{job.status}}",  "resultUrl": "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}" }'